---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deploy1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
        version: "latest"
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:latest-jdk11
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 2
            periodSeconds: 15
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 10
            successThreshold: 3
            failureThreshold: 3


  


